name: ssh-docker-run
author: skyfury <littleboyfury@gmail.com>
description: ssh server, docker pull image and docker run container
branding:
  icon: 'home'
  color: 'blue'
inputs:
  deploy_token:
    description: 'ssh server private key base64 string (cat id_rsa | base64)'
    required: true
  server_host:
    description: 'server connect url (username@host)'
    required: true
  docker_host:
    description: 'docker connect host (ccr.ccs.tencentyun.com)'
    required: true
  docker_username:
    description: 'docker login username'
    required: true
  docker_password:
    description: 'docker login password'
    required: true
  docker_image_url:
    description: 'docker image url'
    required: true
  docker_image_tag:
    description: 'image tag (latest)'
    required: true
    default: 'latest'
  docker_container_name:
    description: 'docker container name'
    required: true
  docker_options:
    description: 'docker options'
    required: true
    default: '-itd'

runs:
  using: 'docker'
  image: 'Dockerfile'
